config/routes.rb
Blog3::Application.routes.draw do 
  resources :posts do
    resources :comments
  end

  devise_for :users
  resources :users
  root :to => 'posts#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  attr_accessible :text
  validates :text, :presence => true
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :text, :title, :user_id
  has_many :comments
  belongs_to :user
  validates :title, :presence=>true, :uniqueness => true
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :posts

  def my_role
    # self.roles.each do |r|
    #   role_name.inject(r.try(:name)
    # end

    self.roles.map { |r| p r.try(:name) }
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def index
		
	end
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment])
		redirect_to post_url(@post)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, :except=>[:index, :show]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    @email = User.find_by_id(@post.user_id).inspect
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new
    # @post = current_user.posts.build
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])
    @post.user_id = current_user.id
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end
	def show
		@user = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navi.html.erb
<%= link_to 'Blog_3', root_path, :class=>'brand' %>
<ul class="nav">
	<% if user_signed_in? %>
		<li>
			<%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
		</li>
	<% else %>
		<li>
			<%= link_to 'Login', new_user_session_path %>
		</li>
	<% end %>
	<% if user_signed_in? %>
		<li>
			<%= link_to 'Edit account', edit_user_registration_path %>
		</li>
		<% if current_user.has_role? :admin %>
			<li>
				<%= link_to 'Admin', users_path %>
			</li>
		<% end %>
	<% else %>
		<li>
			<%= link_to 'Sign Up', new_user_registration_path %>
		</li>
	<% end %>
</ul>

app/views/layouts/application.html.erb
<!-- http://railsapps.github.com/tutorial-rails-bootstrap-devise-cancan.html -->
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "App_Name" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "App_Name" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navi' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation" class="alert-error">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_area :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<!-- <h1>Listing posts</h1>

<table class="table">
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.title %></td>
    <td><%= post.text %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />


 -->

<div class="row">
  <div class="span12">
    <h1>Nino's blog</h1>
  </div>

  <% @posts.each do |post|  %>
      <div class="span12">
        <h2><%= link_to post.title, post %></h2>
      </div>
      <div class="span12">
        <h6><%= time_ago_in_words(post.created_at) %></h6>
      </div>
      <div class="span12">
        <div><%= post.text %></div>
      </div>
      <div class="span12">
        <% if user_signed_in? %>
          <% if current_user.id = post.user_id %>
            <%= link_to 'Edit', edit_post_path(post) %>  |
          <% end %>
          <% if current_user.has_role? :admin %>
            <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?'} %>
          <% end %>
        <% end %>
      </div>
      <div class="span12">
        <hr>
      </div>  
  <% end %>
  <div class="span12">
    <%= link_to 'New Post', new_post_path %>
  </div>

</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Text:</b>
  <%= @post.text %>
</p>

<p>
	<b>User:</b>
	<%= User.find_by_id(@post.user_id).email %>
</p>

<h2>Comments</h2>
<% @post.comments.each do |c| %>
	<p><em>Comment: </em><%= c.text %></p>
	<p><%= time_ago_in_words(c.created_at) %></p>
<% end %>



<h2>Add a comment</h2>
<%= form_for [@post,@post.comments.new], :html=>{:class=>"form-horizontal"} do |f| %>
	<%= f.label "Comment" %>
	<%= f.text_area :text, :id=> 'abc' %>
	<%= f.submit :class=>"btn"%>
<% end %>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/index.html.erb
<h1>Lists of Users</h1>
<% @users.each do |u| %>
	<li>
		<%= link_to u.email, u %>
	</li>
	<dt><%= u.email %></dt>
	<%= u.my_role %>
<% end %>

app/views/users/show.html.erb
<h1>User information</h1>
<ul>
	<li>User <%= @user.id %>: <%= @user.email %></li>
</ul>